from time import sleep
import os
clear = lambda: os.system('cls')
angel = 'miranda'
keuzejalist = ['ja','zeker','duh','tuurlijk','Ja','Zeker','Duh','Tuurlijk','JA','ZEKER','DUH','TUURLIJK']
keuzeneelist = ['nee','nope','zeker niet','ik dacht het niet','Nee','Nope','Zeker niet','Ik dacht het niet','NEE','NOPE','ZEKER NIET','IK DACHT HET NIET',]
skilllist = ['great sage', 'skill tame', 'power absoberen']
mannenstem = ['Onbekende mannen stem']
sage = ['Great sage']
oude_zwaard = 0
coins = 0
def keuze10a():
    print("Je besluit een simpele taak aan te nemen. Het verzamelen van brandhout")
    sleep(3)
    print('10 jaar later…')
    sleep(3)
    print('Grote groep mensen: gejuich')
    sleep(3)
    print('Grote groep mensen: het is de sterkte man ter de wereld')
    sleep(3)
    print('Grote groep mensen: is het het waar dat jij een kandidaat bent om de nieuwe koning te worden',naam)
    sleep(3)
    print(naam,': ja dat klopt al jaren lang is mijn zwaard voor dit land en dat zal nooit veranderen')
    sleep(3)
    print('einde koning')
    sleep(5)
def keuze10b():
    print('je wilt toch geen avonturier worden en besluit de rest van je leven mee te helpen op de markt')
    sleep(3)
    print('10 jaar later')
    print('jouw dochter: papa vertel ons jouw levensverhaal nog eens')
    sleep(3)
    print(naam,': oke maar daarna moeten jullie echt slapen')
    sleep(3)
def keuze9a():
    print('receptionist : er zijn 2 melding die spoedig een bodyguard nodig hebben ')
    sleep(3)
    print(naam,' : doe mij maar de makkelijkste')
    sleep(3)
    print('receptionist : bodyguard jobs weet je nooit hoe moeilijk het is ')
    sleep(3)
    print('je accepteert de job om iemand te beschermen in het bos ')
    sleep(3)
    print('je komt aan in het bos en er verschijnen goblins')
    sleep(3)
    print('baas : versla ze')
    sleep(3)
    print(naam,'maar, ik heb geen wapens')
    sleep(3)
    print('baas:wat?')
    sleep(3)
    print('je word vermoord door de goblins')
    sleep(3)
def keuze9b():
    print('Receptionist : je bent nu een f rank avonturier')
    sleep(3)
    print('Receptionist :  je kunt alleen taken die f rank hebben nemen')
    sleep(3)
    print('Receptionist : hoe meer jobs je doet/ haalt hoe hoger je rank word')
    sleep(3)
    print('Receptionist : wil je een taak nemen')
    keuze10 = input()
    if keuze10 == 'ja':
        keuze10a()
    elif keuze10 == 'nee':
        keuze10b()
    else:
        print('das geen antwoord ')
    


    
def keuze6():
                        keuze6 = input('')
                        if keuze6 == 'klusjes':
                            print(naam,': kan ik iets voor u doen als klusje')
                            sleep(2.6)
                            print('Groenteman: je kan die 8 dozen naar achter brengen voor 20 geld stukken')
                            sleep(2.6)
                            print('Je draagt de laatste doos naar achter en komt een versleten oude zwaard tegen ')
                            #keuze 8 vraag je of je hem mag houden
                            sleep(2.8)
                            print('vraag je of je hem mag houden?')
                            keuze8()

                        elif keuze6 == 'bodyguard':
                            print(naam,': hoe word je iemands bodyguard')
                            print('Groenteman: je kan naar de adverturere guild gaan en aangeven dat je een bodyguard wilt zijn')
                            sleep(3)
                            print(naam,': oke')
                            sleep(3)
                            print('Je loopt langs een aantal hotels en restaurantjes voor dat je aan komt bij de adventurer guild')
                            sleep(3)
                            print('Je komt binnen en vraagt aan de receptie hoe word je een bodyguard')
                            sleep(3)
                            print('Receptionist: ben je al aangesloten aan de guild?')
                            sleep(3)
                            print(naam,': nee')
                            sleep(3)
                            print('receptionist: dat is zo gedaan')
                            #keuze 9
                            keuze9a()
                            


                        elif keuze6 == 'adventurer':
                            print('Je loopt langs een aantal hotels en restaurantjes voor dat je aan komt bij de adventurer guild ')
                            print('Je komt binnen en vraagt aan de receptie wat voor banen ze hebben.')
                            print('Receptionist: ben je al aangesloten bij de guild?')
                            print(naam,': nee')
                            print('receptionist: nou dat is zo gedaan')
                            print('klusjes,bodyguard,adventurer')
                            keuze9b()
                            
                             

                            
                                
                            



def keuze8():
        keuze8 = input('')
        if keuze8 in keuzejalist:
            print(naam,': mag ik hem houden?')
            sleep(2.5)
            print('groenteman : tuurlijk, ik heb er niks aan')
            sleep(3)
            print('De man geeft je wat voedsel en wijst je de weg naar de hotel als bedankje voor het helpen')
            print("je komt aan in een hotel die er heel oud uit ziet ")
            print('hotel-medewerker : 1 nacht kost 5 silver stukken')
            print(naam,"ik heb alleen maar goudstukken bij me ")
            print('hotel-medewerker : ...')
            print('je hoort stemmen aan de achterkant van de hotel')
            print('je geeft de hotel-medewerker 1 goud stuk ')
            print('in de nacht word je spullen gestolen en word je vermoord in je slaap')

        elif keuze8 in keuzeneelist:
            
            print('je besluit om niet te vragen om de zwaard tehouden en gaat weg met de 20 goud stukken')
            sleep(3)
            print('je zoekt naar een slaap plaats en loopt een steeg in')
            sleep(3)          
            print('dieven lopen achter je aan de steeg in en je woord neer gestoken')  
                          
def guildtest1():
    guildtest = input()
    if guildtest == '2':
        print('je bent geslaagt')
    else:
        print('je bent afgewezen')
        
    

while 1:
    print('midas')
    sleep(2)
    print('een game gemaakt door  jamy de waal')
    sleep(2)
    print('veel plezier en duik in het verhaal')
    print("loading . . .")
    sleep(2)
    print('loading . . . .')
    sleep(2)
    print('loading complete')
    sleep(2)
    clear()
    sleep(2)
    # hier begint start 
    print('Je zit in je kamer het is donker en je gordijn is dicht.')
    sleep(2)
    print('Je  start je computer op en gaat aan je bureau zitten.')
    sleep(2)
    print('Je start midas op een mmorpg rpg.')
    sleep(2)
    print('Midas opstartscherm: wat is jouw naam ')
    #naam is de naam van de speler 
    naam = input('')
    sleep(2)
    print('Na 10 uur begin je een beetje hoofd pijn te krijgen en langzaam word alles…')
    sleep(2)
    print('zwart')
    sleep(2)
    print('Je ligt in completen duisternis')
    sleep(2)
    print('In de verte hoor je een stem zachtjes luider worden ')
    sleep(2)
    print('Onbekende stem: Hallo? ….hallo?')
    sleep(2)
    while 1:

        print('Onbekende stem: kun je me horen?')
        keuze1 = input()
        if keuze1 in keuzejalist:
            print('Onbekende stem: geweldig ik ben Miranda ik ben hier om jouw een hergeboorte')
            sleep(2.6)
            print('te geven in een andere wereld. één waar zwaard vechten en magie de norm zijn.')
            sleep(2.6)
            print(naam,':dit is een grap')
            sleep(2.6)
            print(angel,': als ik jou was zou ik dit serieus gaan nemen want je krijgt geen tweede kans',naam)
            sleep(2.6)
            print(naam,':hoe weet je mijn naam?')
            sleep(2.6)
            print(angel,': ik heb hier geen tijd voor je krijgt de  skill great sage voor je nieuwe leven zeg great sage om te bevestigen')
            sleep(2.6)
            keuze2 = input('')
            if keuze2 == 'great sage':
                print(angel,': perfect ')
                sleep(2)
                print(angel,'de skill : great sage')
                sleep(2)
                print(angel,': je kunt nu spreken met de great sage door heb een vraag in je hoofd testellen')
                sleep(2)
                print(angel,':alleen kun je het niet al te vaak gebruiken vanwege … bijwerkingen anyway..')
                sleep(2)
                print(angel,': good luck met je avontuur ik zorg dat je wakker word naast een dorp waar je kan beginnen')
                sleep(2)
                clear()
                print('kling, kling')
                sleep(2)
                print(mannenstem,': ben je nog levend?')
                sleep(2)
                print(mannenstem,': hallo?')
                sleep(2)
                print('Water word over je heen gegooid')
                sleep(2)
                print('je zit gelijk overeind')
                sleep(2.6)
                print(naam,': wat is jouw probleem?')
                sleep(2.6)
                print(mannenstem,': mijn probleem?')
                sleep(2.6)
                print(mannenstem,': ik ben niet degene die bewusteloos ligt buiten de muren van het dorp ')
                sleep(2.6)
                print(mannenstem,': wil je dood ofzo?')
                sleep(2.6)
                print(naam,': dorp? Waar heb je het over?')
                sleep(2.6)
                print(naam,': o wacht dat is wat de god tegen me zei')
                sleep(2.6)
                print(mannenstem,': god?')
                sleep(2.6)
                print('ga je nu vertellen wat er is gebeurd?')
                sleep(2.6)
                keuze3 = input('')
                if keuze3 in keuzejalist:
                    print('Je verteld hem over wat je is overkomen')
                    sleep(2.6)
                    print(mannenstem,': een onderdaan van god ')
                    sleep(2.6)
                    print('Onbekende man word enthousiast')
                    sleep(2.6)
                    print(mannenstem,':  we zijn gered eindelijk ')
                    sleep(2.6)
                    print(naam,': gered?')
                    sleep(2.6)
                    print(mannenstem,': jij komt ons redden van de demonen')
                    sleep(2.6)
                    print(naam,': ja dat denk ik toch niet ')
                    sleep(2.6)
                    print('Onbekende man zegt het tegen de ridders en vertelt dat je geen intensie hebt de demonen te bevechten.')
                    sleep(2.6)
                    print('Je word publiekelijk geëxecuteerd ')
                    sleep(2.6)
                    print('wil je opnieuw')
                    sleep(2.6)
                    restart = input()
                    if restart in keuzejalist:
                        break
                    elif restart in keuzeneelist:
                        quit
                if keuze3 in keuzeneelist:
                    print('Je houd het voor je.')
                    sleep(2.6)
                    print('En de man brengt je in de stad.')
                    sleep(2.6)
                    print('Je loop door een gigantische poort die lijkt alsof het uit een fantasie wereld komt.')
                    sleep(2.6)
                    print('De man blijkt een bewaker van de gate te zijn waar hij jouw vond.')
                    sleep(2.6)
                    print('Hij geeft je een pasje met toestemming om in de stad te blijven.')
                    sleep(2.6)
                    print('Je gaat opzoek naar een plaats om te slapen maar je beseft dat je geen geld hebt.')
                    sleep(2.6)
                    print('Je raakt in paniek en vraagt je zelf af wat je kan doen en dan herinnerde je wat')
                    sleep(2.6)
                    print('Miranda zei je hebt nu de skill great sage en je kon het alles vragen wat je wou en hij zou een antwoord hebben.')
                    sleep(2.6)
                    print('ga je great sage gebruiken')
                    sleep(2.6)
                    keuze4 = input('')
                    if keuze4 in keuzejalist:
                        print(sage,': er is een dungeon 4 km van de west gate vandaan je kunt daar makelijk schatten vinden.')
                        sleep(3)
                        print('ga je naar de dungeon of ga je verder door de stad zoeken')
                        sleep(3)
                        print('dungeon of verder kijken')
                        keuze5 = input('')
                        if keuze5 == 'dungeon':
                            print('Je besluit naar de dungeon te gaan. Onderweg kom je een bos tegen')
                            print('ga je items verzammelen in het bos ja/nee?')
                            keuze7 = input()
                            if keuze7 in keuzejalist:
                                print('Je loopt in de bos en je vindt een tak,klimop en een steen')
                                sleep(3)
                                print('Je maakt een stenen bijl')
                                sleep(3)
                                print('Verder op zie je het pad weer richting  de dungeon.')
                                sleep(3)
                                print('Na 2 uur bereik je eindelijk de dungeon')
                                sleep(3)
                                print('De deur gaat krakend open')
                                sleep(3)
                                print('Je loopt de eerste kamer binnen')
                                sleep(3)
                                print('De vuur korven gaan automatisch aan ')
                                sleep(3)
                                print('Je komt een goblin tegen')
                                sleep(3)
                                print('Je hakt in 1 slag ze hoofd er af met je bijl ')
                                sleep(3)
                                print('pak je zijn mes op?')
                                keuze11 = input()
                                if keuze11 in keuzejalist:
                                    print('ja je pakt het mes op en laat je bijl achter')
                                    sleep(3)
                                    print('in de volgende kamer kom je een goblin tegen met een houten shild en een zwaard')
                                    sleep(3)
                                    print('je slaat met je mes maar de goblin blokt het met zijn schild en hij snijd je nek door')
                                    sleep(3)
                                    break
                                elif keuze11 in keuzeneelist:
                                    print('je laat de mes achter en gaat verder met een bijl ')
                                    sleep(3)
                                    print('in de volgende kamer kom je een goblin tegen')
                                    sleep(3)
                                    print('met een zwaar en een schild ')
                                    sleep(3)
                                    print('je slaat met je bijl ')
                                    sleep(3)
                                    print('de goblin blokt het ')
                                    sleep(3)
                                    print('maar je hakt door het houten schild heen ')
                                    print('*biep* :  level up')
                                    print('Je gaat naar de volgende kamer ')
                                    sleep(3)
                                    print('*boem boem boem*')
                                    print('Boss kamer opent')
                                    sleep(4)
                                    print('Je kan niet meer ontsnappen en word gedwongen te vechten ')
                                    sleep(3)
                                    print('Het is een minotaurs')
                                    print('Je had geen schijn van kans alleen en ging binnen secondes dood')
                                    sleep(8)
                                    break


                        elif keuze5 == 'verder kijken':
                                print('Je besluit om rond te kijken en je vind een markt.')
                                sleep(2.6)
                                print('Groenteman: he knul wil je wat fruit het is het verste uit de hele stad')
                                sleep(2.6)
                                print(naam,': ik heb geen geld, weet u een manier om makelijk geld teverdienen.')
                                sleep(2.6)
                                print('Groenteman: hmm…')
                                sleep(2.6)
                                print('Groenteman: je zou klusjes kunnen doen, je zou een bodyguard kunnen zijn en aan sluiten bij de adventurer guild.')
                                sleep(2.6)
                                keuze6()
                                break
                                        
                        else:
                            print('dat is geen optie')
                            clear()
                    elif keuze4 in keuzeneelist:
                        print('Je besluit om rond te kijken en je vind een markt.')
                        sleep(2.6)
                        print('Groenteman: he knul wil je wat fruit het is het verste uit de hele stad')
                        sleep(2.6)
                        print(naam,': ik heb geen geld, weet u een manier om makelijk geld teverdienen.')
                        sleep(2.6)
                        print('Groenteman: hmm…')
                        sleep(2.6)
                        print('Groenteman: je zou klusjes kunnen doen, je zou een bodyguard kunnen zijn en aan sluiten bij de adventurer guild.')
                        sleep(2.6)
                        keuze6()
                        break
            else:
                print('geen optie probeer nog een keer')


        elif keuze1 in keuzeneelist:
            print('Onbekende stem: ha ha ha heel grappig ')
            print(naam,': weet ik ')
            sleep(2)
            print('angel : mijn naam is miranda.')
            sleep(2)
            print(angel,': ik had een speech klaar staan maar daar heb ik geen zin meer in.')
            sleep(2)
            while 1:
                print(angel,': kort samengevat je gaat naar een nieuwe wereld je krijgt de skill great sage zeg great sage om het te bevestigen')
                sleep(2)
                print(angel,': kies wijs of niet. het boeit mij niet meer')
                sleep(2)
                print(naam,': wacht wat?')
                sleep(2)
                keuze2 = input('')
                if keuze2 == 'great sage':
                        print(angel,': perfect ')
                        sleep(2)
                        print(angel,'de skill : great sage')
                        sleep(2)
                        print(angel,': je kunt nu spreken met de great sage door heb een vraag in je hoofd testellen')
                        sleep(2)
                        print(angel,':alleen kun je het niet al te vaak gebruiken vanwege … bijwerkingen anyway..')
                        sleep(2)
                        print(angel,': good luck met je avontuur ik zorg dat je wakker word naast een dorp waar je kan beginnen')
                        sleep(2)
                        clear()
                        print('kling, kling')
                        sleep(2)
                        print(mannenstem,': ben je nog levend?')
                        sleep(2)
                        print(mannenstem,': hallo?')
                        sleep(2)
                        print('Water word over je heen gegooid')
                        sleep(2)
                        print('je zit gelijk overeind')
                        sleep(2.6)
                        print(naam,': wat is jouw probleem?')
                        sleep(2.6)
                        print(mannenstem,': mijn probleem?')
                        sleep(2.6)
                        print(mannenstem,': ik ben niet degene die bewusteloos ligt buiten de muren van het dorp ')
                        sleep(2.6)
                        print(mannenstem,': wil je dood ofzo?')
                        sleep(2.6)
                        print(naam,': dorp? Waar heb je het over?')
                        sleep(2.6)
                        print(naam,': o wacht dat is wat de god tegen me zei')
                        sleep(2.6)
                        print(mannenstem,': god?')
                        sleep(2.6)
                        print('ga je nu vertellen wat er is gebeurd?')
                        sleep(2.6)
                        keuze3 = input('')
                        if keuze3 in keuzejalist:
                            print('Je verteld hem over wat je is overkomen')
                            sleep(2.6)
                            print(mannenstem,': een onderdaan van god ')
                            sleep(2.6)
                            print('Onbekende man word enthousiast')
                            sleep(2.6)
                            print(mannenstem,':  we zijn gered eindelijk ')
                            sleep(2.6)
                            print(naam,': gered?')
                            sleep(2.6)
                            print(mannenstem,': jij komt ons redden van de demonen')
                            sleep(2.6)
                            print(naam,': ja dat denk ik toch niet ')
                            sleep(2.6)
                            print('Onbekende man zegt het tegen de ridders en vertelt dat je geen intensie hebt de demonen te bevechten.')
                            sleep(2.6)
                            print('Je word publiekelijk geëxecuteerd ')
                            sleep(2.6)
                            print('wil je opnieuw')
                            sleep(2.6)
                            restart = input()
                            if restart in keuzejalist:
                                break
                            elif restart in keuzeneelist:
                                quit
                        if keuze3 in keuzeneelist:
                            print('Je houd het voor je.')
                            sleep(2.6)
                            print('En de man brengt je in de stad.')
                            sleep(2.6)
                            print('Je loop door een gigantische poort die lijkt alsof het uit een fantasie wereld komt.')
                            sleep(2.6)
                            print('De man blijkt een bewaker van de gate te zijn waar hij jouw vond.')
                            sleep(2.6)
                            print('Hij geeft je een pasje met toestemming om in de stad te blijven.')
                            sleep(2.6)
                            print('Je gaat opzoek naar een plaats om te slapen maar je beseft dat je geen geld hebt.')
                            sleep(2.6)
                            print('Je raakt in paniek en vraagt je zelf af wat je kan doen en dan herinnerde je wat')
                            sleep(2.6)
                            print('Miranda zei je hebt nu de skill great sage en je kon het alles vragen wat je wou en hij zou een antwoord hebben.')
                            sleep(2.6)
                            print('ga je great sage gebruiken')
                            sleep(2.6)
                            keuze4 = input('')
                            if keuze4 in keuzejalist:
                                print('Je besluit om rond te kijken en je vind een markt.')
                        sleep(2.6)
                        print('Groenteman: he knul wil je wat fruit het is het verste uit de hele stad')
                        sleep(2.6)
                        print(naam,': ik heb geen geld, weet u een manier om makelijk geld teverdienen.')
                        sleep(2.6)
                        print('Groenteman: hmm…')
                        sleep(2.6)
                        print('Groenteman: je zou klusjes kunnen doen, je zou een bodyguard kunnen zijn en aan sluiten bij de adventurer guild.')
                        sleep(2.6)
                        keuze6()
                        break

                else:
                    print('geen optie probeer nog een keer')
        else:
            print('geen optie probeer nog een keer')